# Generated by Django 2.1.1 on 2018-12-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackLoad',
            fields=[
                ('idBackload', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=45)),
                ('backloadDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BackloadLines',
            fields=[
                ('idBackloadLines', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('idBranch', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('idCashier', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('idBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredProducts',
            fields=[
                ('idDeliveredProducts', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('idDelivery', models.AutoField(primary_key=True, serialize=False)),
                ('deliveryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLines',
            fields=[
                ('idSales', models.AutoField(primary_key=True, serialize=False)),
                ('unitPrice', models.CharField(max_length=45)),
                ('qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('idManager', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('idBranch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLines',
            fields=[
                ('idOrderLines', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('suggestedUnitPrice', models.FloatField()),
                ('unitsInStock', models.IntegerField()),
                ('reorderLevel', models.IntegerField()),
                ('unitOfMeasure', models.CharField(max_length=45)),
                ('SKU', models.IntegerField()),
                ('barcode', models.CharField(max_length=45)),
                ('idCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('idPurchaseOrder', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('expectedDate', models.DateField()),
                ('idCashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Cashier')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('idSales', models.AutoField(primary_key=True, serialize=False)),
                ('invoiceDate', models.DateField()),
                ('customer', models.CharField(max_length=45)),
                ('idCashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Cashier')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('idSupplier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('contactNumber', models.CharField(max_length=45)),
                ('emailAddress', models.CharField(max_length=45)),
                ('website', models.CharField(max_length=45)),
                ('address1', models.CharField(max_length=45)),
                ('address2', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('province', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
                ('postal', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TransferLines',
            fields=[
                ('idTransferOrder', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.FloatField()),
                ('idProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Product')),
            ],
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('idTransferOrder', models.AutoField(primary_key=True, serialize=False)),
                ('transferDate', models.DateField()),
                ('expectedDate', models.DateField()),
                ('idCashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Cashier')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='idSupplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Supplier'),
        ),
        migrations.AddField(
            model_name='orderlines',
            name='idProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Product'),
        ),
        migrations.AddField(
            model_name='orderlines',
            name='idPurchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='invoicelines',
            name='idProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Product'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='idPurchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='deliveredproducts',
            name='idDelivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Delivery'),
        ),
        migrations.AddField(
            model_name='deliveredproducts',
            name='idOrderLines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.OrderLines'),
        ),
        migrations.AddField(
            model_name='backloadlines',
            name='idProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Product'),
        ),
        migrations.AddField(
            model_name='backload',
            name='idCashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salikneta.Cashier'),
        ),
    ]
